version: 2.1

commands:
  install-dagger:
    steps:
      - run:
          name: Install deps
          command: pip install dagger-io
      - run:
          name: Install Dagger CLI
          command: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sudo sh; cd -; }
jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - install-dagger
      - run:
          name: Run Dagger pipeline
          command: dagger run --progress plain python ./ci/build.py
      - persist_to_workspace:
          root: ~/
        
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - install-dagger
      - run:
          name: Run Dagger pipeline
          command: dagger run --progress plain python ./ci/deploy.py
workflows:
  dagger:
    jobs:
      - build
      - deploy:
          requires:
            - build